services:
  weviko-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: weviko-engine:local
    container_name: weviko-engine
    env_file:
      - .env
    environment:
      PORT: 10000
    init: true
    ipc: host
    ports:
      - "10000:10000"
    security_opt:
      - seccomp=./seccomp_profile.json
    restart: unless-stopped
